version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - CerealBoy
  assignees:
  - CerealBoy
  ignore:
  - dependency-name: github.com/gin-gonic/gin
    versions:
    - 1.7.0
  - dependency-name: github.com/jmoiron/sqlx
    versions:
    - 1.3.1
